### PR TITLE
Subgraph end-to-end scripts

### PR DESCRIPTION
**Pull request by ryley-o**
Add reference subgraph end-to-end tests for the V3 core contract and minter suite.

I'm not completely sure if this is a great thing to add to our smart contracts repo, but it does seem like a useful reference to have when we want to test updates to our subgraph.

I added two additional testnet private keys to support the artist address being different than the superAdmin, and another etc. address 

script logs:
```
Admin ACL attached to at 0x0D277C3d488CdABD86DB37E743765835e273101E
GenArt721Core attached to at 0xF396C180bb2f92EE28535D23F5224A5b9425ceca
Minter Filter attached to at 0x7EcFFfc1A3Eb7Ce76D4b29Df3e5098D2D921D367
MinterSetPrice V2 attached to at 0x3A23Ae9EB73C14Ff2A83a0bBe1028A690006e0cc
MinterSetPrice ERC20 V2 attached to at 0x004E1cdb723869f6c65086f1d5cED55Cd9BA1971
Minter DA Lin V2 attached to at 0x73873eAAf65338256E31b1e612AC74D09492B5B8
Minter DA Exp V2 attached to at 0xBced47092b6c1a9Ee24aFeC871E782aA44587001
Minter Merkle V1 attached to at 0xcd1AA5C612731108267D22b77745207D9728Edf8
Minter Holder V1 attached to at 0x82Df93Cd9Cd9178C8F442FB766fe3402916Fe567
Project A added to GenArt721Core with projectId 109
Project B added to GenArt721Core at 110
Updated the Minter Filter on the Core contract to 0x7EcFFfc1A3Eb7Ce76D4b29Df3e5098D2D921D367
approved minter on MinterFilter: 0x3A23Ae9EB73C14Ff2A83a0bBe1028A690006e0cc.
removed minter on MinterFilter: 0x3A23Ae9EB73C14Ff2A83a0bBe1028A690006e0cc.
approved minter on MinterFilter: 0x3A23Ae9EB73C14Ff2A83a0bBe1028A690006e0cc
approved minter on MinterFilter: 0x004E1cdb723869f6c65086f1d5cED55Cd9BA1971
approved minter on MinterFilter: 0x73873eAAf65338256E31b1e612AC74D09492B5B8
approved minter on MinterFilter: 0xBced47092b6c1a9Ee24aFeC871E782aA44587001
approved minter on MinterFilter: 0xcd1AA5C612731108267D22b77745207D9728Edf8
approved minter on MinterFilter: 0x82Df93Cd9Cd9178C8F442FB766fe3402916Fe567
set price per token for Project A to 1000000000000000
set auction details for Project A
set minter to set price for Project A
set minter to DAEXP for Project A
removed minter for Project A
set minter to set price for Project A
set minter to set price for Project B
updated core curation registry address to 0x894f73632F6c39801d77b76da78fc22Cb3a1a0dE
updated core dependency registry address to 0x894f73632F6c39801d77b76da78fc22Cb3a1a0dE
updated core primary sales address to 0x3c6412FEE019f5c50d6F03Aa6F5045d99d9748c4
updated core secondary sales address to 0x3c6412FEE019f5c50d6F03Aa6F5045d99d9748c4
updated core AB primary sales percentage to 12
updated core AB secondary sales BPS to 251
toggled project active for project A, projectId: 109
updated project A name to be: Project A
updated project A artist name to be: Scripty
added project A script
added another project A script
removed last project A script
updated project A script type and version to p5js@1.0.0
updated project A script type and version to 1.77777778
toggled project paused for project A, projectId: 109
updated project A royalty percentage to: 6
updated project A website
updated project A max invocations to: 100
proposed artist addresses and splits for project A
admin accepted addresses and splits for project A
updated project A description
minted a token for project A
TESTING COMPLETE!
```

### CODE REVIEW

**Comment by jakerockland** [comment]
> I'm not completely sure if this is a great thing to add to our smart contracts repo, but it does seem like a useful reference to have when we want to test updates to our subgraph.

My inclination here is that it may make more sense to add these to the subgraphs repo instead and import the contracts repo as a submodule of that repo? Alternatively, we could consider merging the subgraph and contracts repos into a single repo. 

WDYT @ryley-o @yoshiwarab @lyaunzbe ?

**Comment by ryley-o** [comment]
I don't have any very strong opinions where this lives, other than it should probably live somewhere. I think it makes most sense to be ran in the smart contracts repo since it requires hardhat, but it is mostly reference, and could be stored as reference material in the subgraph repo.
combining the two repos makes sense in a lot of ways, but I kind of like our current distinct separation of "things that change immutable smart contracts" and "things that change our indexing layer" 🤷

**Comment by jakerockland** [comment]
> I don't have any very strong opinions where this lives, other than it should probably live somewhere. I think it makes most sense to be ran in the smart contracts repo since it requires hardhat, but it is mostly reference, and could be stored as reference material in the subgraph repo. combining the two repos makes sense in a lot of ways, but I kind of like our current distinct separation of "things that change immutable smart contracts" and "things that change our indexing layer" 🤷

Hrm, given a bit more thought here, my hot take would be that subgraph repo should import contracts repo as a submodule (as the contracts are a dependency for the subgraph, not the other way around / not a chicken-and-egg problem) and then we add the functionality-set of these changes in subgraph repo instead. 

Does that seem reasonable / congruent with your outlook above @ryley-o ?

**Comment by ryley-o** [comment]
>Hrm, given a bit more thought here, my hot take would be that subgraph repo should import contracts repo as a submodule (as the contracts are a dependency for the subgraph, not the other way around / not a chicken-and-egg problem) and then we add the functionality-set of these changes in subgraph repo instead.

Does that seem reasonable / congruent with your outlook above @ryley-o ?

Yeah that generally makes sense. That solution requires some duplication of env vars since we need wallets and api keys to run the scripts, but I think that is preferable as opposed to combining the entire repos 😄

**Comment by ryley-o** [comment]
based on the discussion above, going to go ahead and close this, and open an issue in the subgraph repo.

**Pull request closed without merging**
