### PR TITLE
Add deployment log + minter suite details for Collaborations

### PR DESCRIPTION
**Pull request by jakerockland**
## Description of the change

Add deployment details to this repository for the 3 Collaborations/Engine V3 contracts deployed at EOY '22, and add details for full-minter suites deployed for the "Art Blocks x Pace" and "Art Blocks x Bright Moments" Collaborations.

### CODE REVIEW

**Comment by jakerockland** [comment]
Deployment details for **Art Blocks x Pace goerli-artist-staging** deployment, given the following input params:

```
// Art Blocks V3 Core Staging (Goerli)
const CORE_CONTRACT_ADDRESS = "0x0eba0bd3702d850EEc7a8215EB53FFC293c42341";
// MinterFilterV1
const FILTER_CONTRACT_ADDRESS = "0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328";
// Note: deployed w/ same mainnet/testnet address
const DELEGATION_REGISTRY_ADDRESS =
  "0x00000000000076A84feF008CDAbe6409d2FE638B";
```

Full deployment log running `yarn hardhat run scripts/1_reference_minter_suite_minter_deployer.ts --network goerli`:

```
Using MinterFilterV1 deployed at 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterDAExpV4 deployed at 0x5d292CFfD4e3EA08049760D42F8F67bcde4E9260
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
Duplicate definition of ResetAuctionDetails (ResetAuctionDetails(uint256), ResetAuctionDetails(uint256,uint256,uint256))
MinterDAExpSettlementV1 deployed at 0x8ABdb5c40BB6593550ff0027d15D8B6BEc416a24
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterDALinV4 deployed at 0x1353fd9d3dC70d1a18149C8FB2ADB4FB906DE4E8
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterHolderV4 deployed at 0xA3ae49B0fE17A0735dBc9f11Fb51122687DbC27E
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterMerkleV5 deployed at 0x8F7DbE58B34710510E44FE9d513e54F01729c686
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterSetPriceV4 deployed at 0xde6DCA519049473Da8826c57B4F45f6dE7f22a73
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterSetPriceERC20V4 deployed at 0x0D4BeE9AfbB364cF32F37912845C770A4badd83E
REMINDER: Allowlist these minters on your MinterFilterV1 deployed at: 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328
If automated verification below fails, verify deployment with:
yarn hardhat verify --network goerli 0x5d292CFfD4e3EA08049760D42F8F67bcde4E9260 0x0eba0bd3702d850EEc7a8215EB53FFC293c42341 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328
yarn hardhat verify --network goerli 0x8ABdb5c40BB6593550ff0027d15D8B6BEc416a24 0x0eba0bd3702d850EEc7a8215EB53FFC293c42341 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328
yarn hardhat verify --network goerli 0x1353fd9d3dC70d1a18149C8FB2ADB4FB906DE4E8 0x0eba0bd3702d850EEc7a8215EB53FFC293c42341 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328
yarn hardhat verify --network goerli 0xA3ae49B0fE17A0735dBc9f11Fb51122687DbC27E 0x0eba0bd3702d850EEc7a8215EB53FFC293c42341 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328 0x00000000000076A84feF008CDAbe6409d2FE638B
yarn hardhat verify --network goerli 0x8F7DbE58B34710510E44FE9d513e54F01729c686 0x0eba0bd3702d850EEc7a8215EB53FFC293c42341 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328 0x00000000000076A84feF008CDAbe6409d2FE638B
yarn hardhat verify --network goerli 0xde6DCA519049473Da8826c57B4F45f6dE7f22a73 0x0eba0bd3702d850EEc7a8215EB53FFC293c42341 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328
yarn hardhat verify --network goerli 0x0D4BeE9AfbB364cF32F37912845C770A4badd83E 0x0eba0bd3702d850EEc7a8215EB53FFC293c42341 0x5E22FBBB6bb2C45aE060b4C96f5039efdF7Fb328
Nothing to compile
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDAExpV4.sol:MinterDAExpV4 at 0x5d292CFfD4e3EA08049760D42F8F67bcde4E9260
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDAExpV4 on Etherscan.
https://goerli.etherscan.io/address/0x5d292CFfD4e3EA08049760D42F8F67bcde4E9260#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDAExpSettlementV1.sol:MinterDAExpSettlementV1 at 0x8ABdb5c40BB6593550ff0027d15D8B6BEc416a24
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDAExpSettlementV1 on Etherscan.
https://goerli.etherscan.io/address/0x8ABdb5c40BB6593550ff0027d15D8B6BEc416a24#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDALinV4.sol:MinterDALinV4 at 0x1353fd9d3dC70d1a18149C8FB2ADB4FB906DE4E8
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDALinV4 on Etherscan.
https://goerli.etherscan.io/address/0x1353fd9d3dC70d1a18149C8FB2ADB4FB906DE4E8#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterHolderV4.sol:MinterHolderV4 at 0xA3ae49B0fE17A0735dBc9f11Fb51122687DbC27E
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterHolderV4 on Etherscan.
https://goerli.etherscan.io/address/0xA3ae49B0fE17A0735dBc9f11Fb51122687DbC27E#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterMerkleV5.sol:MinterMerkleV5 at 0x8F7DbE58B34710510E44FE9d513e54F01729c686
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterMerkleV5 on Etherscan.
https://goerli.etherscan.io/address/0x8F7DbE58B34710510E44FE9d513e54F01729c686#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterSetPriceV4.sol:MinterSetPriceV4 at 0xde6DCA519049473Da8826c57B4F45f6dE7f22a73
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterSetPriceV4 on Etherscan.
https://goerli.etherscan.io/address/0xde6DCA519049473Da8826c57B4F45f6dE7f22a73#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterSetPriceERC20V4.sol:MinterSetPriceERC20V4 at 0x0D4BeE9AfbB364cF32F37912845C770A4badd83E
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterSetPriceERC20V4 on Etherscan.
https://goerli.etherscan.io/address/0x0D4BeE9AfbB364cF32F37912845C770A4badd83E#code
✨  Done in 497.27s.

```

**Comment by jakerockland** [comment]
Deployment details for **Art Blocks x Pace mainnet** deployment, given the following input params:

```
const CORE_CONTRACT_ADDRESS = "0xEa698596b6009A622C3eD00dD5a8b5d1CAE4fC36";
// MinterFilterV1
const FILTER_CONTRACT_ADDRESS = "0xc89c6dfDE92AacD293AF930bD8D290a33D35eEf0";
// Note: deployed w/ same mainnet/testnet address
const DELEGATION_REGISTRY_ADDRESS =
  "0x00000000000076A84feF008CDAbe6409d2FE638B";
```

Full deployment log running `yarn hardhat run scripts/1_reference_minter_suite_minter_deployer.ts --network mainnet`:

```


```

**Comment by jakerockland** [comment]
Deployment details for **Art Blocks x Bright Moments goerli-artist-staging** deployment, given the following input params:

```
const CORE_CONTRACT_ADDRESS = "0x5112c52535449513c81bDF113b8DCC757d7f122b";
// MinterFilterV1
const FILTER_CONTRACT_ADDRESS = "0x75b123eAcBf813804bAc83e1D6e5c3d1758746e6";
// Note: deployed w/ same mainnet/testnet address
const DELEGATION_REGISTRY_ADDRESS =
  "0x00000000000076A84feF008CDAbe6409d2FE638B";
```

Full deployment log running `yarn hardhat run scripts/1_reference_minter_suite_minter_deployer.ts --network goerli`:

```

```

**Comment by jakerockland** [comment]
Deployment details for **Art Blocks x Bright Moments mainnet** deployment, given the following input params:

```
const CORE_CONTRACT_ADDRESS = "0x145789247973C5D612bF121e9E4Eef84b63Eb707";
// MinterFilterV1
const FILTER_CONTRACT_ADDRESS = "0x6E522449C1642E7cB0B12a2889CcBf79b51C69f8";
// Note: deployed w/ same mainnet/testnet address
const DELEGATION_REGISTRY_ADDRESS =
  "0x00000000000076A84feF008CDAbe6409d2FE638B";
```

Full deployment log running `yarn hardhat run scripts/1_reference_minter_suite_minter_deployer.ts --network goerli`:

```

```

**Review by ryley-o — APPROVED** [review]
LGTM!

**Pull request merged**
