### PR TITLE
Remove Enumerable conformance for PBAB and PRTNR

### PR DESCRIPTION
**Pull request by jakerockland**
~~This PR is very much just a draft/proposal.~~

~~That said,~~ I don't think that there is a meaningful enough divergence in functionality when removing `Enumerable` conformance that we need to treat this as a new version for our templates, but open to feedback here to the contrary.

There is a big enough gas savings from removing this in V3 that I am inclined to remove from PBAB/PRTNR templates **now** rather than waiting until V4 (the new PBAB/PRTNR standard/template that we should pursue as a follow on once V3 is 🚢 'd)~~, but would love additional input from @ryley-o @yoshiwarab @lyaunzbe before moving this out of draft mode.~~

~~WDYT folks?~~

### CODE REVIEW

**Comment by jakerockland** [comment]
Other rationale for doing this now (vs. waiting for V4) is coalescing with changes in https://github.com/ArtBlocks/artblocks-contracts/pull/204, which will be merged soon. 😄

**Comment by ryley-o** [comment]
Yeah, I don't think this affects anything downstream in our pipeline, so kind of an easy yes from me.
If we have to make any non-negligible changes to our frontend, this might be not worth it, but I suspect nothing will change at all.
If we want to support existing partners upgrading to this core, we will need a constructor arg or something to indicate first project ID.

**Comment by jakerockland** [comment]
> If we want to support existing partners upgrading to this core, we will need a constructor arg or something to indicate first project ID. (would also like input from the Bens on this!)

Great point, we probably should do that either in this PR or follow up. Going to wait to get more feedback from Ben or Ben before updating this PR but that SGTM.

**Comment by yoshiwarab** [comment]
Yeah, I don't see any issue with removing enumerable conformance straight away. The only thing that feels somewhat useful is being able to check the total supply to sanity check our indexing quickly. Still, there are definitely plenty of other sanity checks we can do instead.

**Comment by yoshiwarab** [comment]
> If we want to support existing partners upgrading to this core, we will need a constructor arg or something to indicate first project ID. (would also like input from the Bens on this!)

Also definitely think we should add this and wondering if we'd also like to add some mechanism to v3 to prevent adding new projects once we've switched over to a new core contract.

**Comment by jakerockland** [comment]
> wondering if we'd also like to add some mechanism to v3 to prevent adding new projects once we've switched over to a new core contract.

This seems like a good idea–low cost to do so.

**Comment by ryley-o** [comment]
> Also definitely think we should add this and wondering if we'd also like to add some mechanism to v3 to prevent adding new projects once we've switched over to a new core contract.

Ready for your review ser! https://github.com/ArtBlocks/artblocks-contracts/pull/255 😄

**Comment by jakerockland** [comment]
Tests are updated 😄 

Ready for review/merge @ryley-o

**Review by ryley-o — APPROVED** [review]
LGTM 🎉

**Pull request merged**
