### PR TITLE
Deploy AB x BMG polyptych minter

### PR DESCRIPTION
**Pull request by jakerockland**
## Description of the change

Deployment details for AB x BMG polyptych minter.

Allowlisted on the https://etherscan.io/address/0x6E522449C1642E7cB0B12a2889CcBf79b51C69f8#code minterfilter here:

https://etherscan.io/tx/0xf7170599ceb592f2e297154bbc8371b34b21f908315e36873819e7cafd72e866

### CODE REVIEW

**Comment by jakerockland** [comment]
> @jakerockland - I pushed a commit that fixes the issue you were encountering 🙏 this should be g2g, and I'm able to deploy a polyptych minter on dev now 👍

Thank you thank you thank you!!

**Review by ryley-o — APPROVED** [review]
Love it! 🙌 
Cc @shantanubala - and just want to note that there are some follow-on actions before polyptych will be WAI (e.g. setting "hash seed setter contract" on the polyptych randomizer, IIUC)

**Comment by jakerockland** [comment]
> Love it! 🙌 Cc @shantanubala - and just want to note that there are some follow-on actions before polyptych will be WAI (e.g. setting "hash seed setter contract" on the polyptych randomizer, IIUC)

Do we have a good run-book of those items written out anywhere @ryley-o @shantanubala ?

> setting "hash seed setter contract" on the polyptych randomizer

Regarding this step specifically, I believe that was done already w/ this step (copy-pasting from #minter-suite in Slack) unless I'm misunderstanding the suggestion:

- https://etherscan.io/address/0xb6d59ccc0d35e7233c2d284fda735823acd91bb0 +
https://etherscan.io/tx/0x167c03082763d4f1682c165ac5e1455e0f73853b3cdbbaf46ac28b55c2d5d1cf

**Comment by ryley-o** [comment]
>Regarding this step specifically, I believe that was done already w/ this step (copy-pasting from #minter-suite in Slack) unless I'm misunderstanding the suggestion:

Ah, @jakerockland @shantanubala - specifically, I think the following call was incorrect in that it set the core contract as the hash seed setter contract: https://etherscan.io/tx/0x8583bc529a823e84bf69e5592b0f1799cbbc9a58205faa258e7e6b03a63c6f41

I think the same function should be called on the randomizer, but with the new polyptych minter's address as the input arg. Does that make sense?

re: run-book, we have a somewhat messy list of steps that were completed during testing the polyptych minter on dev [here](https://docs.google.com/document/d/1MC9KKzOkSHcnl_W3PUHT7iOrXzQFBino2ksK09Zb-EQ/edit?usp=sharing)...  @shantanubala do you have anything easier to follow than my messy notes 😅

**Comment by shantanubala** [comment]
@ryley-o @jakerockland Here's a doc with instructions, let me know if you have any questions / ideas for improving them: https://www.notion.so/artblocks/Polyptych-Minter-a69117099caf40fe8adefa8b19257fc4?pvs=4

**Pull request merged**
