### PR TITLE
V3 Contract Architecture Diagrams

### LINKED ISSUE #508: Incorporate architecture diagrams in the documentation within this repo
@ryley-o an idea for a future polish week

### PR DESCRIPTION
**Pull request by ryley-o**
## Description of the change

Add Diagrams that depict the V3 core contract's architecture, including AdminACL, Randomizer, Engine Registry, and Flex Dependencies.

Fixes #508 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204177667808642

### CODE REVIEW

**Comment by ryley-o** [comment]
Also tagging @lyaunzbe since this adds a Flex Dependencies diagram 🙏

**Review by jakerockland — APPROVED** [review]
Totally churn right now to do this–not suggesting we do this now–(and not as high-fidelity as using draw) but a neat thing to explore in the future for more inline diagrams that are more readily adjustable alongside code adjustments in PRs. Could be useful for less-detailed/higher-altitude relationship diagram type view in the future: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by jakerockland** [comment]
> Also tagging @lyaunzbe since this adds a Flex Dependencies diagram 🙏

We should include the new on-chain dependency type I think for the Flex diagram.

**Comment by jakerockland** [comment]
This is fantastic 🔥 🙏 

Thank you for spending the time to put these together @ryley-o

**Comment by ryley-o** [comment]
>Totally churn right now to do this–not suggesting we do this now–(and not as high-fidelity as using draw) but a neat thing to explore in the future for more inline diagrams that are more readily adjustable alongside code adjustments in PRs. Could be useful for less-detailed/higher-altitude relationship diagram type view in the future: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

Oh yes, very cool and I think definitely could help describe some relationships in this repo 🙏 thanks for sharing!

**Comment by ryley-o** [comment]
>We should include the new on-chain dependency type I think for the Flex diagram.

Updated in commit [1fdff67](https://github.com/ArtBlocks/artblocks-contracts/pull/572/commits/1fdff671dd3013f0d6726461211a6b3c0d1a3316)

**Comment by ryley-o** [comment]
I think I'll go ahead and merge this, but a quick check retroactively by @lyaunzbe re: flex diagram would still be much appreciated 🙏 thanks!

**Pull request merged**
