### PR TITLE
Add script for deploying latest set of full-suite minters

### PR DESCRIPTION
**Pull request by jakerockland**
## Description of the change

Intended to be deployed on mainnet + goerli with the following respective details:

```
// GOERLI (ARTIST-STAGING) ADDRESSSES
// Art Blocks V3 Core Staging (Goerli)
const CORE_CONTRACT_ADDRESS = "0xb614c578062a62714c927cd8193f0b8bfb90055c";
// MinterFilterV1
const FILTER_CONTRACT_ADDRESS = "0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC";
// Note: deployed w/ same mainnet/testnet address
const DELEGATION_REGISTRY_ADDRESS = "0x00000000000076A84feF008CDAbe6409d2FE638B";
```
&
```
// MAINNET ADDRESSES
// Art Blocks (BLOCKS)
const CORE_CONTRACT_ADDRESS = "0x99a9B7c1116f9ceEB1652de04d5969CcE509B069";
// MinterFilterV1
const FILTER_CONTRACT_ADDRESS = "0x092B8F64e713d66b38522978BCf4649db14b931E";
// Note: deployed w/ same mainnet/testnet address
const DELEGATION_REGISTRY_ADDRESS = "0x00000000000076A84feF008CDAbe6409d2FE638B";
```

> reminder: Any mainnet deployments after 10 Jan 2023 should be tagged as [Releases](https://github.com/ArtBlocks/artblocks-contracts/releases) in this repository. This ensures that the deployed contract source code is easily verifiable by anyone.

### CODE REVIEW

**Comment by jakerockland** [comment]
Converting to draft for now, until README/this PR is updated with deployed details after this script is run.

**Review by ryley-o — APPROVED** [review]
LGTM - just a reminder to not allowlist these on mainnet quite yet, as that would break our mainnet subgraph deployment (which doesn't include the updates that remove the constraint of minter types on the MinterTypes enum).

**Comment by jakerockland** [comment]
Goerli (artist-staging targetted) deployment run, full log from running `yarn hardhat run scripts/1_reference_minter_suite_minter_deployer.ts --network goerli`:

```
Using MinterFilterV1 deployed at 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterDAExpV4 deployed at 0x6FBbfbdbF71D319c5F007C9DF1c2ae63b3F463a6
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
Duplicate definition of ResetAuctionDetails (ResetAuctionDetails(uint256), ResetAuctionDetails(uint256,uint256,uint256))
MinterDAExpSettlementV1 deployed at 0xCee138625d669b49bDde0Bf1600A2EaF29C2C9C8
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterDALinV4 deployed at 0x99980fEa1397a33E7058E01A73099bfF81d310d2
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterHolderV4 deployed at 0x0EA91da0C3338f88510cBB2a3cf20Cd1863551a8
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterMerkleV5 deployed at 0x8632212Fca423fe868C6C93c59DCcAdAB59f4e41
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterSetPriceV4 deployed at 0xb5629f232cE932E214Fb548Ed049795b04e58FB9
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterSetPriceERC20V4 deployed at 0x7a1Ee96dCAF0b65Abc68D78D12b81523360838E1
REMINDER: Allowlist these minters on your MinterFilterV1 deployed at: 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC
If automated verification below fails, verify deployment with:
yarn hardhat verify --network goerli 0x6FBbfbdbF71D319c5F007C9DF1c2ae63b3F463a6 0xb614c578062a62714c927cd8193f0b8bfb90055c 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC
yarn hardhat verify --network goerli 0xCee138625d669b49bDde0Bf1600A2EaF29C2C9C8 0xb614c578062a62714c927cd8193f0b8bfb90055c 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC
yarn hardhat verify --network goerli 0x99980fEa1397a33E7058E01A73099bfF81d310d2 0xb614c578062a62714c927cd8193f0b8bfb90055c 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC
yarn hardhat verify --network goerli 0x0EA91da0C3338f88510cBB2a3cf20Cd1863551a8 0xb614c578062a62714c927cd8193f0b8bfb90055c 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC 0x00000000000076A84feF008CDAbe6409d2FE638B
yarn hardhat verify --network goerli 0x8632212Fca423fe868C6C93c59DCcAdAB59f4e41 0xb614c578062a62714c927cd8193f0b8bfb90055c 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC 0x00000000000076A84feF008CDAbe6409d2FE638B
yarn hardhat verify --network goerli 0xb5629f232cE932E214Fb548Ed049795b04e58FB9 0xb614c578062a62714c927cd8193f0b8bfb90055c 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC
yarn hardhat verify --network goerli 0x7a1Ee96dCAF0b65Abc68D78D12b81523360838E1 0xb614c578062a62714c927cd8193f0b8bfb90055c 0x6eA558Bb1A3C5437970AdA80f8c686448A9c31fC
Nothing to compile
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDAExp/MinterDAExpV4.sol:MinterDAExpV4 at 0x6FBbfbdbF71D319c5F007C9DF1c2ae63b3F463a6
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDAExpV4 on Etherscan.
https://goerli.etherscan.io/address/0x6FBbfbdbF71D319c5F007C9DF1c2ae63b3F463a6#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDAExpSettlement/MinterDAExpSettlementV1.sol:MinterDAExpSettlementV1 at 0xCee138625d669b49bDde0Bf1600A2EaF29C2C9C8
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDAExpSettlementV1 on Etherscan.
https://goerli.etherscan.io/address/0xCee138625d669b49bDde0Bf1600A2EaF29C2C9C8#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDALin/MinterDALinV4.sol:MinterDALinV4 at 0x99980fEa1397a33E7058E01A73099bfF81d310d2
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDALinV4 on Etherscan.
https://goerli.etherscan.io/address/0x99980fEa1397a33E7058E01A73099bfF81d310d2#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterHolder/MinterHolderV4.sol:MinterHolderV4 at 0x0EA91da0C3338f88510cBB2a3cf20Cd1863551a8
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterHolderV4 on Etherscan.
https://goerli.etherscan.io/address/0x0EA91da0C3338f88510cBB2a3cf20Cd1863551a8#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterMerkle/MinterMerkleV5.sol:MinterMerkleV5 at 0x8632212Fca423fe868C6C93c59DCcAdAB59f4e41
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterMerkleV5 on Etherscan.
https://goerli.etherscan.io/address/0x8632212Fca423fe868C6C93c59DCcAdAB59f4e41#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterSetPrice/MinterSetPriceV4.sol:MinterSetPriceV4 at 0xb5629f232cE932E214Fb548Ed049795b04e58FB9
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterSetPriceV4 on Etherscan.
https://goerli.etherscan.io/address/0xb5629f232cE932E214Fb548Ed049795b04e58FB9#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterSetPriceERC20/MinterSetPriceERC20V4.sol:MinterSetPriceERC20V4 at 0x7a1Ee96dCAF0b65Abc68D78D12b81523360838E1
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterSetPriceERC20V4 on Etherscan.
https://goerli.etherscan.io/address/0x7a1Ee96dCAF0b65Abc68D78D12b81523360838E1#code
✨  Done in 481.54s.
```

Consolidated read-out of deployed+verified minters:

```
Successfully verified contract MinterDAExpV4 on Etherscan.
https://goerli.etherscan.io/address/0x6FBbfbdbF71D319c5F007C9DF1c2ae63b3F463a6#code

Successfully verified contract MinterDAExpSettlementV1 on Etherscan.
https://goerli.etherscan.io/address/0xCee138625d669b49bDde0Bf1600A2EaF29C2C9C8#code

Successfully verified contract MinterDALinV4 on Etherscan.
https://goerli.etherscan.io/address/0x99980fEa1397a33E7058E01A73099bfF81d310d2#code

Successfully verified contract MinterHolderV4 on Etherscan.
https://goerli.etherscan.io/address/0x0EA91da0C3338f88510cBB2a3cf20Cd1863551a8#code

Successfully verified contract MinterMerkleV5 on Etherscan.
https://goerli.etherscan.io/address/0x8632212Fca423fe868C6C93c59DCcAdAB59f4e41#code

Successfully verified contract MinterSetPriceV4 on Etherscan.
https://goerli.etherscan.io/address/0xb5629f232cE932E214Fb548Ed049795b04e58FB9#code

Successfully verified contract MinterSetPriceERC20V4 on Etherscan.
https://goerli.etherscan.io/address/0x7a1Ee96dCAF0b65Abc68D78D12b81523360838E1#code

```

**Comment by jakerockland** [comment]
Mainnet deployment run, full log from running `yarn hardhat run scripts/1_reference_minter_suite_minter_deployer.ts --network mainnet`:

```
Compiled 181 Solidity files successfully
Using MinterFilterV1 deployed at 0x092B8F64e713d66b38522978BCf4649db14b931E
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterDAExpV4 deployed at 0x47e2df2723238f913741Cc6b1963e76fdfD19B94
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
Duplicate definition of ResetAuctionDetails (ResetAuctionDetails(uint256), ResetAuctionDetails(uint256,uint256,uint256))
MinterDAExpSettlementV1 deployed at 0xfdE58c821D1c226b4a45c22904de20b114EDe7E7
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterDALinV4 deployed at 0x419501DD208BFf237e3E32C40D074065e12DfF4d
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterHolderV4 deployed at 0xCCFF562017bdAAa064184b3Eb9bd892d8Acce7d6
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterMerkleV5 deployed at 0xB8Bd1D2836C466DB149f665F777928bEE267304d
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterSetPriceV4 deployed at 0x234B25288011081817B5cC199C3754269cCb76D2
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
MinterSetPriceERC20V4 deployed at 0x9fEcd2FbC6D890fB93632DcE9b1a01c4090A7E2d
REMINDER: Allowlist these minters on your MinterFilterV1 deployed at: 0x092B8F64e713d66b38522978BCf4649db14b931E
If automated verification below fails, verify deployment with:
yarn hardhat verify --network mainnet 0x47e2df2723238f913741Cc6b1963e76fdfD19B94 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
yarn hardhat verify --network mainnet 0xfdE58c821D1c226b4a45c22904de20b114EDe7E7 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
yarn hardhat verify --network mainnet 0x419501DD208BFf237e3E32C40D074065e12DfF4d 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
yarn hardhat verify --network mainnet 0xCCFF562017bdAAa064184b3Eb9bd892d8Acce7d6 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E 0x00000000000076A84feF008CDAbe6409d2FE638B
yarn hardhat verify --network mainnet 0xB8Bd1D2836C466DB149f665F777928bEE267304d 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E 0x00000000000076A84feF008CDAbe6409d2FE638B
yarn hardhat verify --network mainnet 0x234B25288011081817B5cC199C3754269cCb76D2 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
yarn hardhat verify --network mainnet 0x9fEcd2FbC6D890fB93632DcE9b1a01c4090A7E2d 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
Nothing to compile
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDAExp/MinterDAExpV4.sol:MinterDAExpV4 at 0x47e2df2723238f913741Cc6b1963e76fdfD19B94
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDAExpV4 on Etherscan.
https://etherscan.io/address/0x47e2df2723238f913741Cc6b1963e76fdfD19B94#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDAExpSettlement/MinterDAExpSettlementV1.sol:MinterDAExpSettlementV1 at 0xfdE58c821D1c226b4a45c22904de20b114EDe7E7
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDAExpSettlementV1 on Etherscan.
https://etherscan.io/address/0xfdE58c821D1c226b4a45c22904de20b114EDe7E7#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterDALin/MinterDALinV4.sol:MinterDALinV4 at 0x419501DD208BFf237e3E32C40D074065e12DfF4d
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterDALinV4 on Etherscan.
https://etherscan.io/address/0x419501DD208BFf237e3E32C40D074065e12DfF4d#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterHolder/MinterHolderV4.sol:MinterHolderV4 at 0xCCFF562017bdAAa064184b3Eb9bd892d8Acce7d6
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterHolderV4 on Etherscan.
https://etherscan.io/address/0xCCFF562017bdAAa064184b3Eb9bd892d8Acce7d6#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterMerkle/MinterMerkleV5.sol:MinterMerkleV5 at 0xB8Bd1D2836C466DB149f665F777928bEE267304d
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterMerkleV5 on Etherscan.
https://etherscan.io/address/0xB8Bd1D2836C466DB149f665F777928bEE267304d#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterSetPrice/MinterSetPriceV4.sol:MinterSetPriceV4 at 0x234B25288011081817B5cC199C3754269cCb76D2
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterSetPriceV4 on Etherscan.
https://etherscan.io/address/0x234B25288011081817B5cC199C3754269cCb76D2#code
Compiled 181 Solidity files successfully
Successfully submitted source code for contract
contracts/minter-suite/Minters/MinterSetPriceERC20/MinterSetPriceERC20V4.sol:MinterSetPriceERC20V4 at 0x9fEcd2FbC6D890fB93632DcE9b1a01c4090A7E2d
for verification on the block explorer. Waiting for verification result...

Successfully verified contract MinterSetPriceERC20V4 on Etherscan.
https://etherscan.io/address/0x9fEcd2FbC6D890fB93632DcE9b1a01c4090A7E2d#code
✨  Done in 501.97s.

```

Consolidated read-out of deployed+verified minters:

```
Successfully verified contract MinterDAExpV4 on Etherscan.
https://etherscan.io/address/0x47e2df2723238f913741Cc6b1963e76fdfD19B94#code

Successfully verified contract MinterDAExpSettlementV1 on Etherscan.
https://etherscan.io/address/0xfdE58c821D1c226b4a45c22904de20b114EDe7E7#code

Successfully verified contract MinterDALinV4 on Etherscan.
https://etherscan.io/address/0x419501DD208BFf237e3E32C40D074065e12DfF4d#code

Successfully verified contract MinterHolderV4 on Etherscan.
https://etherscan.io/address/0xCCFF562017bdAAa064184b3Eb9bd892d8Acce7d6#code

Successfully verified contract MinterMerkleV5 on Etherscan.
https://etherscan.io/address/0xB8Bd1D2836C466DB149f665F777928bEE267304d#code

Successfully verified contract MinterSetPriceV4 on Etherscan.
https://etherscan.io/address/0x234B25288011081817B5cC199C3754269cCb76D2#code

Successfully verified contract MinterSetPriceERC20V4 on Etherscan.
https://etherscan.io/address/0x9fEcd2FbC6D890fB93632DcE9b1a01c4090A7E2d#code
```

**Comment by jakerockland** [comment]
@ryley-o something to loop back and jam on–not sure what format/standard we want to use for https://github.com/ArtBlocks/artblocks-contracts/tags to add a tag for this release appropriately.

**Pull request merged**
