### PR TITLE
Prototype contract as script storage

### PR DESCRIPTION
**Pull request by ryley-o**
⚠️ This is a prototype, do not merge. Much more investigation required.

Many things to do before we decide if we want to implement this.

## Gas impacts
Very large script upload gas improvement. Example script upload cost impacts are shown in the table below.

_All gas costs assume project 3 mints avg(501-516) of 1000_
| Gas Test | Previous gas to upload script | New gas used to upload script | % change |
| --- | --- | --- | --- |
| GenArt721CoreV3: Upload Squiggle Script | 2_822_470 | 943_967 | -66.6% |
| GenArt721CoreV3: Upload Skulptuur-like Script | 4_569_796 | 1_493_682 | -67.3% |

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202817061735237

### CODE REVIEW

**Comment by jakerockland** [comment]
Very interesting–would be awesome to profile how this impacts max upload size as well per "chunk".

**Comment by ryley-o** [comment]
>Very interesting–would be awesome to profile how this impacts max upload size as well per "chunk".

Do we have a way that we currently calculate the max size per "chunk"?

**Comment by jakerockland** [comment]
> > Very interesting–would be awesome to profile how this impacts max upload size as well per "chunk".
> 
> Do we have a way that we currently calculate the max size per "chunk"?

I don't think so explicitly, but it will be basically defacto limited to what the gas limit is per block–as IIUC this is what impacts the amount that can be written into storage w/ a string in one "chunk"?

**Comment by ryley-o** [comment]
>I don't think so explicitly, but it will be basically defacto limited to what the gas limit is per block–as IIUC this is what impacts the amount that can be written into storage w/ a string in one "chunk"?

Ah, that makes sense!

**Comment by ryley-o** [comment]
I guess if this saves roughly 2/3, we should be able to have 3x larger chunks.

**Comment by jakerockland** [comment]
> I guess if this saves roughly 2/3, we should be able to have 3x larger chunks. I can find the limits via test though.

Yeah good point! Wasn't sure if there were other limits on contract upload size other than gas limits.

**Comment by ryley-o** [comment]
>Yeah good point! Wasn't sure if there were other limits on contract upload size other than gas limits.

This is true - 24kb is thee limit. Looks like our current chunks are about 10kb max, so probably closer to ~2.4x larger chunks.

**Comment by ryley-o** [comment]
closing in favor of #299

**Pull request closed without merging**
