### PR TITLE
V3/mainnet deployer script

### PR DESCRIPTION
**Pull request by ryley-o**
Add deployer script for deployment of V3 core to Ethereum mainnet.

## Overview
The added script may be used to deploy V3 core mainnet and associated minter suite, AdminACLV0, and simple randomizer to the Ethereum mainnet.

Note that the core contract's randomizer may be updated at a later date by the superAdmin.

## TODO before deployment
@jakerockland - please define the following items in the script. I've included suggested values, but please double-check.

- [x] define `superAdminAddress` on line 35
  - this is the AdminACL's superAdmin address, and should be a multisig
  - suggested: current admin on V1: `0x96dC73c8B5969608C77375F085949744b5177660`
- [x] define `artblocksPrimarySalesAddress` on line 36
  - this is address that receives primary sales payments
  - suggested: current `artblocksAddress` on V1 core is `0xf7A55108A6E830a809e88e74cbf5f5DE9D930153`
- [x] define `artblocksSecondarySalesAddress` on line 37
  - this is the address that receives secondary sales royalty payments
  - suggested: current value for V1 on royalty registry is `0x05b0658C6D0eD423e39da60F8feDDd460d838F5f`
- [x] confirm `tokenName` and `tokenTicker` are not desired to be changed relative to the V1 core contract, on lines 33 & 34
- [x] compile + generate typechain BEFORE running deployment script 😄 

## TODO after deployment

- [x] upload deployment logs in this PR
- [x] verify all contracts on etherscan

## A note on salted contract creations
It should be noted that implementing a salted, create2-style deployment to achieve a more gas-efficient contract address (i.e. an address with many zero-bytes) was not prioritized during V3 core deployment. We implement Ownable, so would require some additional logic to implement a create2 deployment, albeit only minor logic updates. Other than enabling a quicker development timeline and less complexity during deployment, a minor benefit to not using salted contract creations is that users can be assured our contract cannot be re-created at the same address after being deployed (see Warning in [this section](https://docs.soliditylang.org/en/v0.8.17/control-structures.html?highlight=create2#salted-contract-creations-create2) of solidity documentation).

### CODE REVIEW

**Comment by jakerockland** [comment]
Full deployment script log:

```
➜  artblocks-contracts git:(deploy-v3-mainnet) yarn hardhat run scripts/core-suite-testnet-deployments/1_reference_mainnet_flagship_V3Core_deployer.ts --network mainnet
yarn run v1.22.17
$ /Users/jake/Code/artblocks-contracts/node_modules/.bin/hardhat run scripts/core-suite-testnet-deployments/1_reference_mainnet_flagship_V3Core_deployer.ts --network mainnet
 ·-------------------------------------------|-------------·
 |  Contract Name                            ·  Size (KB)  │
 ············································|··············
 |  Address                                  ·      0.085  │
 ············································|··············
 |  Address                                  ·      0.086  │
 ············································|··············
 |  Address                                  ·      0.086  │
 ············································|··············
 |  Address                                  ·      0.085  │
 ············································|··············
 |  AdminACLV0                               ·      1.863  │
 ············································|··············
 |  BasicRandomizer                          ·      0.335  │
 ············································|··············
 |  BasicRandomizerV2                        ·      1.121  │
 ············································|··············
 |  BytecodeStorage                          ·      0.086  │
 ············································|··············
 |  BytecodeTextCR_DMock                     ·      2.522  │
 ············································|··············
 |  Bytes32Strings                           ·      0.086  │
 ············································|··············
 |  Counters                                 ·      0.085  │
 ············································|··············
 |  Counters                                 ·      0.085  │
 ············································|··············
 |  CustomERC721Metadata                     ·      5.222  │
 ············································|··············
 |  CustomERC721Metadata                     ·      4.597  │
 ············································|··············
 |  DeadReceiverMock                         ·      0.141  │
 ············································|··············
 |  Enum                                     ·      0.063  │
 ············································|··············
 |  EnumerableMap                            ·      0.086  │
 ············································|··············
 |  EnumerableSet                            ·      0.086  │
 ············································|··············
 |  ERC20                                    ·      2.208  │
 ············································|··············
 |  ERC20Mock                                ·      2.208  │
 ············································|··············
 |  ERC721                                   ·      3.359  │
 ············································|··············
 |  ERC721                                   ·      4.585  │
 ············································|··············
 |  ERC721                                   ·      3.984  │
 ············································|··············
 |  ERC721Enumerable                         ·      4.195  │
 ············································|··············
 |  ERC721Enumerable                         ·      4.820  │
 ············································|··············
 |  ERC721_PackedHashSeed                    ·      4.289  │
 ············································|··············
 |  EtherPaymentFallback                     ·      0.122  │
 ············································|··············
 |  Executor                                 ·      0.063  │
 ············································|··············
 |  FallbackManager                          ·      0.427  │
 ············································|··············
 |  GenArt721CoreV1                          ·     24.359  │
 ············································|··············
 |  GenArt721CoreV2_ArtBlocksXPace           ·     16.516  │
 ············································|··············
 |  GenArt721CoreV2_ArtCode                  ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_BrightMoments            ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_BrightMomentsFlex        ·     18.925  │
 ············································|··············
 |  GenArt721CoreV2_ColorsAndShapes          ·     16.469  │
 ············································|··············
 |  GenArt721CoreV2_CryptoCitizens           ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_DoodleLabs               ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_EndaomentGalleryForGood  ·     15.429  │
 ············································|··············
 |  GenArt721CoreV2_ENGINE_FLEX              ·     18.925  │
 ············································|··············
 |  GenArt721CoreV2_Fireworks                ·     16.469  │
 ············································|··············
 |  GenArt721CoreV2_Flutter                  ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_LegendsOfMetaterra       ·     16.469  │
 ············································|··············
 |  GenArt721CoreV2_MechSuit                 ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_PBAB                     ·     15.429  │
 ············································|··············
 |  GenArt721CoreV2_Plottables               ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_PRTNR                    ·     15.476  │
 ············································|··············
 |  GenArt721CoreV2_TBOA                     ·     21.283  │
 ············································|··············
 |  GenArt721CoreV2_VerseFlex                ·     18.925  │
 ············································|··············
 |  GenArt721CoreV3                          ·     23.743  │
 ············································|··············
 |  GenArt721LegacyMinter                    ·      9.114  │
 ············································|··············
 |  GenArt721MinterBurner_PBAB               ·     10.990  │
 ············································|··············
 |  GenArt721Minter_ArtCode                  ·     10.245  │
 ············································|··············
 |  GenArt721Minter_BrightMoments            ·     10.245  │
 ············································|··············
 |  GenArt721Minter_BrightMomentsFlex        ·     10.799  │
 ············································|··············
 |  GenArt721Minter_ColorsAndShapes          ·     10.799  │
 ············································|··············
 |  GenArt721Minter_CryptoCitizens           ·     10.245  │
 ············································|··············
 |  GenArt721Minter_DoodleLabs               ·     10.209  │
 ············································|··············
 |  GenArt721Minter_EndaomentGalleryForGood  ·     10.799  │
 ············································|··············
 |  GenArt721Minter_Fireworks                ·     10.799  │
 ············································|··············
 |  GenArt721Minter_LegendsOfMetaterra       ·     10.799  │
 ············································|··············
 |  GenArt721Minter_MechSuit                 ·     10.245  │
 ············································|··············
 |  GenArt721Minter_PBAB                     ·     10.799  │
 ············································|··············
 |  GenArt721Minter_Plottables               ·     10.245  │
 ············································|··············
 |  GenArt721Minter_TBOA                     ·     10.245  │
 ············································|··············
 |  GenArt721Minter_VerseFlex                ·     10.799  │
 ············································|··············
 |  GenArt721RoyaltyOverride                 ·      2.785  │
 ············································|··············
 |  GenArt721RoyaltyOverride_PBAB            ·      3.701  │
 ············································|··············
 |  GnosisSafe                               ·     12.097  │
 ············································|··············
 |  GnosisSafeMath                           ·      0.086  │
 ············································|··············
 |  GnosisSafeMock                           ·     12.097  │
 ············································|··············
 |  GnosisSafeProxy                          ·      0.123  │
 ············································|··············
 |  GnosisSafeProxyFactory                   ·      2.565  │
 ············································|··············
 |  GnosisSafeProxyFactoryMock               ·      2.565  │
 ············································|··············
 |  GuardManager                             ·      0.340  │
 ············································|··············
 |  ISignatureValidatorConstants             ·      0.063  │
 ············································|··············
 |  MerkleProof                              ·      0.086  │
 ············································|··············
 |  MinterDAExpV0                            ·      8.191  │
 ············································|··············
 |  MinterDAExpV1                            ·      6.993  │
 ············································|··············
 |  MinterDAExpV2                            ·      6.000  │
 ············································|··············
 |  MinterDALinV0                            ·      8.034  │
 ············································|··············
 |  MinterDALinV1                            ·      6.836  │
 ············································|··············
 |  MinterDALinV2                            ·      5.864  │
 ············································|··············
 |  MinterFilterV0                           ·      6.003  │
 ············································|··············
 |  MinterFilterV1                           ·      5.345  │
 ············································|··············
 |  MinterHolderV0                           ·      9.241  │
 ············································|··············
 |  MinterHolderV1                           ·      8.106  │
 ············································|··············
 |  MinterMerkleV0                           ·      7.859  │
 ············································|··············
 |  MinterMerkleV1                           ·      6.500  │
 ············································|··············
 |  MinterSetPriceERC20V0                    ·      9.890  │
 ············································|··············
 |  MinterSetPriceERC20V1                    ·      8.678  │
 ············································|··············
 |  MinterSetPriceERC20V2                    ·      6.853  │
 ············································|··············
 |  MinterSetPriceV0                         ·      6.255  │
 ············································|··············
 |  MinterSetPriceV1                         ·      5.050  │
 ············································|··············
 |  MinterSetPriceV2                         ·      3.754  │
 ············································|··············
 |  MockAdminACLV0Events                     ·      1.265  │
 ············································|··············
 |  ModuleManager                            ·      2.341  │
 ············································|··············
 |  MultiSend                                ·      0.594  │
 ············································|··············
 |  MultiSendMock                            ·      0.594  │
 ············································|··············
 |  OwnerManager                             ·      2.606  │
 ············································|··············
 |  RandomizerV2_NoAssignMock                ·      1.199  │
 ············································|··············
 |  Randomizer_ArtCode                       ·      0.196  │
 ············································|··············
 |  Randomizer_BrightMoments                 ·      0.196  │
 ············································|··············
 |  Randomizer_CryptoCitizens                ·      0.196  │
 ············································|··············
 |  Randomizer_DoodleLabs                    ·      0.196  │
 ············································|··············
 |  Randomizer_Flutter                       ·      0.196  │
 ············································|··············
 |  Randomizer_MechSuit                      ·      0.196  │
 ············································|··············
 |  Randomizer_Plottables                    ·      0.196  │
 ············································|··············
 |  Randomizer_TBOA                          ·      0.196  │
 ············································|··············
 |  ReentrancyHolderMock                     ·      0.874  │
 ············································|··············
 |  ReentrancyMerkleMock                     ·      1.244  │
 ············································|··············
 |  ReentrancyMock                           ·      0.637  │
 ············································|··············
 |  SafeCast                                 ·      0.086  │
 ············································|··············
 |  SafeMath                                 ·      0.085  │
 ············································|··············
 |  SafeMath                                 ·      0.085  │
 ············································|··············
 |  SafeMath                                 ·      0.085  │
 ············································|··············
 |  SecuredTokenTransfer                     ·      0.063  │
 ············································|··············
 |  SelfAuthorized                           ·      0.063  │
 ············································|··············
 |  SignatureDecoder                         ·      0.063  │
 ············································|··············
 |  Singleton                                ·      0.063  │
 ············································|··············
 |  StorageAccessible                        ·      0.756  │
 ············································|··············
 |  Strings                                  ·      0.085  │
 ············································|··············
 |  Strings                                  ·      0.085  │
 ············································|··············
 |  Strings                                  ·      0.086  │
 ············································|··············
 |  Strings                                  ·      0.086  │
 ·-------------------------------------------|-------------·
Randomizer deployed at 0x9dF9dc3Fe9985aa4e1F93543f5a20688f49E6dCa
Admin ACL deployed at 0x39F0e1e8Df2C135Df35B3FA496e943ac4B90Fe0f
GenArt721Core deployed at 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069
Minter Filter deployed at 0x092B8F64e713d66b38522978BCf4649db14b931E
MinterSetPrice V2 deployed at 0x7B7917e083CeA6d9f6a3060a7330c1072fcb4e40
MinterSetPrice ERC20 V2 deployed at 0xe4c6EeF13649e9C4Ad8ae8A9C7fA9A7F26B4287a
Minter DA Lin V2 deployed at 0xdaa6D1e224f4B9f7c4f1368C362C4333A8e385A6
Minter DA Exp V2 deployed at 0x706d6C6ef700a3c1C3a727f0c46492492E0A72b5
Duplicate definition of ConfigValueAddedToSet (ConfigValueAddedToSet(uint256,bytes32,uint256), ConfigValueAddedToSet(uint256,bytes32,address), ConfigValueAddedToSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueRemovedFromSet (ConfigValueRemovedFromSet(uint256,bytes32,uint256), ConfigValueRemovedFromSet(uint256,bytes32,address), ConfigValueRemovedFromSet(uint256,bytes32,bytes32))
Duplicate definition of ConfigValueSet (ConfigValueSet(uint256,bytes32,bool), ConfigValueSet(uint256,bytes32,uint256), ConfigValueSet(uint256,bytes32,address), ConfigValueSet(uint256,bytes32,bytes32))
Minter Merkle V1 deployed at 0xae5A48D22Cd069c4d72dDe204A7fB4B302e614af
Minter Holder V1 deployed at 0xa198E22C32879f4214a37eB3051525bD9aff9145
Updated the Minter Filter on the Core contract.
Updated the artblocks primary sales payment address to: 0xf7A55108A6E830a809e88e74cbf5f5DE9D930153.
Updated the artblocks secondary sales payment address to: 0x05b0658C6D0eD423e39da60F8feDDd460d838F5f.
Allowlisted minter 0x7B7917e083CeA6d9f6a3060a7330c1072fcb4e40 on minter filter.
Allowlisted minter 0xe4c6EeF13649e9C4Ad8ae8A9C7fA9A7F26B4287a on minter filter.
Allowlisted minter 0xdaa6D1e224f4B9f7c4f1368C362C4333A8e385A6 on minter filter.
Allowlisted minter 0x706d6C6ef700a3c1C3a727f0c46492492E0A72b5 on minter filter.
Allowlisted minter 0xae5A48D22Cd069c4d72dDe204A7fB4B302e614af on minter filter.
Allowlisted minter 0xa198E22C32879f4214a37eB3051525bD9aff9145 on minter filter.
Verify core contract deployment with:
yarn hardhat verify --network mainnet 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 "Art Blocks" "BLOCKS" 0x9dF9dc3Fe9985aa4e1F93543f5a20688f49E6dCa 0x39F0e1e8Df2C135Df35B3FA496e943ac4B90Fe0f 374
Verify Admin ACL contract deployment with:
yarn hardhat verify --network mainnet 0x39F0e1e8Df2C135Df35B3FA496e943ac4B90Fe0f
Verify MinterFilter deployment with:
yarn hardhat verify --network mainnet 0x092B8F64e713d66b38522978BCf4649db14b931E 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069
Verify MinterSetPrice deployment with:
yarn hardhat verify --network mainnet 0x7B7917e083CeA6d9f6a3060a7330c1072fcb4e40 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
Verify MinterSetPriceERC20 deployment with:
yarn hardhat verify --network mainnet 0xe4c6EeF13649e9C4Ad8ae8A9C7fA9A7F26B4287a 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
Verify MinterDALin deployment with:
yarn hardhat verify --network mainnet 0xdaa6D1e224f4B9f7c4f1368C362C4333A8e385A6 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
Verify MinterDAExp deployment with:
yarn hardhat verify --network mainnet 0x706d6C6ef700a3c1C3a727f0c46492492E0A72b5 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
Verify MinterMerkle deployment with:
yarn hardhat verify --network mainnet 0xae5A48D22Cd069c4d72dDe204A7fB4B302e614af 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
Verify MinterHolder deployment with:
yarn hardhat verify --network mainnet 0xa198E22C32879f4214a37eB3051525bD9aff9145 0x99a9B7c1116f9ceEB1652de04d5969CcE509B069 0x092B8F64e713d66b38522978BCf4649db14b931E
✨  Done in 298.01s.
```

**Comment by jakerockland** [comment]
Verification log:

```
Successfully verified contract GenArt721CoreV3 on Etherscan.
https://etherscan.io/address/0x99a9B7c1116f9ceEB1652de04d5969CcE509B069#code

Successfully verified contract AdminACLV0 on Etherscan.
https://etherscan.io/address/0x39F0e1e8Df2C135Df35B3FA496e943ac4B90Fe0f#code

Successfully verified contract MinterFilterV1 on Etherscan.
https://etherscan.io/address/0x092B8F64e713d66b38522978BCf4649db14b931E#code

Successfully verified contract MinterSetPriceV2 on Etherscan.
https://etherscan.io/address/0x7B7917e083CeA6d9f6a3060a7330c1072fcb4e40#code

Successfully verified contract MinterSetPriceERC20V2 on Etherscan.
https://etherscan.io/address/0xe4c6EeF13649e9C4Ad8ae8A9C7fA9A7F26B4287a#code

Successfully verified contract MinterDALinV2 on Etherscan.
https://etherscan.io/address/0xdaa6D1e224f4B9f7c4f1368C362C4333A8e385A6#code

Successfully verified contract MinterDAExpV2 on Etherscan.
https://etherscan.io/address/0x706d6C6ef700a3c1C3a727f0c46492492E0A72b5#code

Successfully verified contract MinterMerkleV1 on Etherscan.
https://etherscan.io/address/0xae5A48D22Cd069c4d72dDe204A7fB4B302e614af#code

Successfully verified contract MinterHolderV1 on Etherscan.
https://etherscan.io/address/0xa198E22C32879f4214a37eB3051525bD9aff9145#code
```

**Comment by jakerockland** [comment]
Flagging that this context is hanging – https://etherscan.io/tx/0x307ff9463470ce47ecc0605257298a72a3c30881d6c209b51eb6667c8a5c97c1

Going to just let it sit for a bit, but later today can revoke and re-initiate if needed.

**Comment by jakerockland** [comment]
@ryley-o I think we should be all set 🔥 🔥 🔥 Congratulations and great work here again on all of this.

Before I start doing any shell creation queuing via the multi-sig, could you PTAL at the deployment log / verification log details above and make sure that everything LG from your perspective?

**Comment by ryley-o** [comment]
ty @jakerockland! deployment logs LGTM!

**Comment by jakerockland** [comment]
@ryley-o we good to merge this one (wanted to defer to you as author)?

**Pull request merged**
