### PR TITLE
Add excess settlement funds getter to DA w/Settlement

### PR DESCRIPTION
**Pull request by ryley-o**
Add excess settlement funds getter to DA w/Settlement to reduce latency on frontend.

This should allow our frontend to reduce latency associated with sync times when a user is reclaiming excess funds posted to the DA w/Settlement for a given project.

Cc @Jbern16 

note: subgraph PRs have been updated with abis as of commit e5ba0a1

### CODE REVIEW

**Comment by ryley-o** [comment]
Note that if ABIs are affected beyond commit a5ba0a1, ABIs should be updated in the subgraph and frontend.
Cc @jakerockland & @Jbern16 🙏

**Review by Jbern16 — APPROVED** [review]

**Comment by ryley-o** [comment]
@jakerockland - just wanted to flag this as something that should go in before deploying 🙏

**Review by jakerockland — APPROVED** [review]
Apologies for the delay in review here – this LGTM!

**Comment by jakerockland** [comment]
@Jbern16 should be able to get things deployed to dev tomorrow, Thursday at latest, very sorry for the delay here has been a more hectic start to the week than expected.

**Pull request merged**
